name: Rust

on:
  push:
    branches: [ "dev", "master" ]
  pull_request:
    branches: [ "dev", "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: sudo apt-get install -y libasound2-dev portaudio19-dev build-essential libpulse-dev libdbus-1-dev 
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    #- name: Run tests
    #  run: cargo test --verbose
